#!/usr/bin/env bash

for i in $(vgrep 'github.com\/kubernetes-sigs\/application'|grep '.go');do 
  ex -s $i << APPLICATION
%s/github.com\/kubernetes-sigs\/application\//sigs.k8s.io\/application\/v2\//
w
q
APPLICATION
done

for i in $(vgrep 'k8s.io\/apimachinery\/'|grep '.go');do 
  ex -s $i << APIMACHINERY
%s/k8s.io\/apimachinery\//k8s.io\/apimachinery\/v2\//
w
q
APIMACHINERY
done

for i in $(vgrep 'k8s.io\/api\/'|grep '.go');do 
  ex -s $i << API
%s/k8s.io\/api\//k8s.io\/api\/v2\//
w
q
API
done

for i in $(vgrep 'k8s.io\/apiextensions-apiserver\/'|grep '.go');do 
  ex -s $i << APIEXTENSIONS_APISERVER
%s/k8s.io\/apiextensions-apiserver\//k8s.io\/apiextensions-apiserver\/v2\//
w
q
APIEXTENSIONS_APISERVER
done

for i in $(vgrep 'k8s.io\/client-go\/'|grep '.go');do 
  ex -s $i << CLIENT_GO
%s/k8s.io\/client-go\//k8s.io\/client-go\/v2\//
w
q
CLIENT_GO
done

for i in $(vgrep 'sigs.k8s.io\/controller-runtime\/'|grep '.go');do 
  ex -s $i << CONTROLLER_RUNTIME
%s/sigs.k8s.io\/controller-runtime\//sigs.k8s.io\/controller-runtime\/v2\//
w
q
CONTROLLER_RUNTIME
done
